use gpui_kit::SharedString;

use super::types::FALLBACK;

/// The icon name for an extension, or the plain file.
pub fn icon_for_extension(ext: &str) -> &'static str {
    by_extension(&ext.trim_start_matches('.').to_lowercase()).unwrap_or(FALLBACK)
}

/// The icon a file's own name carries, if any, from the last part of `path`.
pub fn icon_for_name(path: &str) -> Option<&'static str> {
    let path = strip_location(path);
    let name = path.rsplit(['/', '\\']).next().unwrap_or(path);
    by_name(&name.to_lowercase())
}

/// The asset path of a file's icon.
pub fn file_icon(path: &str) -> SharedString {
    let path = strip_location(path);
    if let Some(icon) = icon_for_name(path) {
        return asset(icon);
    }
    let name = path.rsplit(['/', '\\']).next().unwrap_or(path).to_lowercase();
    let icon = if name.ends_with(".d.ts") {
        "typescript-def"
    } else {
        match name.rsplit_once('.') {
            Some((_, ext)) => icon_for_extension(ext),
            None => FALLBACK,
        }
    };
    asset(icon)
}

/// The asset path of a folder's icon, open or closed. A merged folder row ("crates/beui/src") takes its
/// last folder's.
pub fn folder_icon(name: &str, open: bool) -> SharedString {
    let last = name.rsplit(['/', '\\']).find(|p| !p.is_empty()).unwrap_or(name).to_lowercase();
    let icon = special_folder(&last).unwrap_or("folder");
    if open { format!("file-icons/{icon}-open.svg").into() } else { asset(icon) }
}

/// The embedded SVG at an asset path, for [`crate::Assets`].
pub(crate) fn bytes(path: &str) -> Option<&'static [u8]> {
    embedded(path.strip_prefix("file-icons/")?.strip_suffix(".svg")?)
}

pub(super) fn asset(icon: &str) -> SharedString {
    format!("file-icons/{icon}.svg").into()
}

/// `foo.ts:12` and `foo.ts:12:4` are `foo.ts`.
pub(crate) fn strip_location(path: &str) -> &str {
    let mut out = path;
    for _ in 0..2 {
        match out.rsplit_once(':') {
            Some((head, tail)) if !tail.is_empty() && tail.bytes().all(|b| b.is_ascii_digit()) => out = head,
            _ => break,
        }
    }
    out
}

/// File names that carry their own icon, lower case (acepe's `filenameToIcon`).
pub(super) fn by_name(name: &str) -> Option<&'static str> {
    match name {
        "dockerfile" | "docker-compose.yml" | "docker-compose.yaml" => Some("docker"),
        "makefile" => Some("makefile"),
        "cmakelists" => Some("cmake"),
        "package.json" | "package-lock.json" => Some("npm"),
        "pnpm-lock.yaml" => Some("pnpm"),
        "yarn.lock" => Some("yarn"),
        "bun.lockb" => Some("bun"),
        "cargo.toml" | "cargo.lock" => Some("rust"),
        "go.mod" | "go.sum" => Some("go-mod"),
        "gemfile" | "gemfile.lock" | "rakefile" => Some("ruby"),
        "tsconfig.json" => Some("tsconfig"),
        "jsconfig.json" => Some("jsconfig"),
        ".gitignore" | ".gitattributes" | ".gitmodules" => Some("git"),
        ".env" | ".env.local" | ".env.development" | ".env.production" => Some("tune"),
        ".editorconfig" => Some("editorconfig"),
        ".eslintrc" | ".eslintrc.js" | ".eslintrc.json" | ".eslintrc.yml" => Some("eslint"),
        ".prettierrc" | ".prettierrc.js" | ".prettierrc.json" | "prettier.config.js" => Some("prettier"),
        "vite.config.ts" | "vite.config.js" => Some("vite"),
        "webpack.config.js" | "webpack.config.ts" => Some("webpack"),
        "rollup.config.js" | "rollup.config.ts" => Some("rollup"),
        "svelte.config.js" | "svelte.config.ts" => Some("svelte"),
        "tailwind.config.js" | "tailwind.config.ts" => Some("tailwindcss"),
        "postcss.config.js" => Some("postcss"),
        "vitest.config.ts" | "vitest.config.js" => Some("vitest"),
        "jest.config.js" | "jest.config.ts" => Some("jest"),
        "license" | "license.md" | "license.txt" => Some("license"),
        "readme" | "readme.md" | "readme.txt" => Some("readme"),
        "changelog" | "changelog.md" => Some("changelog"),
        "todo" | "todo.md" => Some("todo"),
        "turbo.json" => Some("turborepo"),
        "biome.json" => Some("biome"),
        ".nvmrc" | ".node-version" => Some("nodejs"),
        "deno.json" | "deno.jsonc" => Some("deno"),
        _ => None,
    }
}

/// Extensions, lower case and without the dot (acepe's `extensionToIcon`).
pub(super) fn by_extension(ext: &str) -> Option<&'static str> {
    match ext {
        "ts" | "mts" | "cts" => Some("typescript"),
        "tsx" => Some("react_ts"),
        "d.ts" => Some("typescript-def"),
        "js" | "mjs" | "cjs" => Some("javascript"),
        "jsx" => Some("react"),
        "svelte" => Some("svelte"),
        "vue" => Some("vue"),
        "astro" => Some("astro"),
        "py" | "pyw" | "pyc" | "pyo" | "pyi" => Some("python"),
        "rs" | "ron" => Some("rust"),
        "go" => Some("go"),
        "mod" => Some("go-mod"),
        "java" | "jar" | "jsp" => Some("java"),
        "class" => Some("javaclass"),
        "kotlin" | "kt" | "kts" => Some("kotlin"),
        "scala" => Some("scala"),
        "groovy" => Some("groovy"),
        "gradle" => Some("gradle"),
        "clj" | "cljs" => Some("clojure"),
        "c" | "h" => Some("c"),
        "cpp" | "cc" | "cxx" | "hpp" | "hxx" => Some("cpp"),
        "cs" => Some("csharp"),
        "fs" | "fsx" => Some("fsharp"),
        "rb" | "erb" | "rake" | "gemfile" => Some("ruby"),
        "php" => Some("php"),
        "swift" => Some("swift"),
        "hs" | "lhs" => Some("haskell"),
        "ml" | "mli" => Some("ocaml"),
        "ex" | "exs" => Some("elixir"),
        "erl" | "hrl" => Some("erlang"),
        "lua" => Some("lua"),
        "luau" => Some("luau"),
        "pl" | "pm" => Some("perl"),
        "r" | "R" => Some("r"),
        "dart" => Some("dart"),
        "zig" => Some("zig"),
        "nim" => Some("nim"),
        "jl" => Some("julia"),
        "html" | "htm" | "xhtml" => Some("html"),
        "md" | "markdown" | "mdx" => Some("markdown"),
        "tex" | "latex" => Some("tex"),
        "css" => Some("css"),
        "scss" | "sass" => Some("sass"),
        "less" => Some("less"),
        "styl" => Some("stylus"),
        "json" | "jsonc" | "json5" | "jsonl" | "ndjson" => Some("json"),
        "yaml" | "yml" => Some("yaml"),
        "toml" => Some("toml"),
        "xml" => Some("xml"),
        "svg" => Some("svg"),
        "csv" | "parquet" => Some("table"),
        "sh" | "bash" | "zsh" | "fish" => Some("console"),
        "ps1" | "psm1" | "psd1" => Some("powershell"),
        "sql" | "sqlite" => Some("database"),
        "prisma" => Some("prisma"),
        "dockerfile" | "docker" => Some("docker"),
        "makefile" => Some("makefile"),
        "cmake" => Some("cmake"),
        "lock" => Some("lock"),
        "gitignore" | "gitattributes" | "gitmodules" => Some("git"),
        "env" => Some("tune"),
        "ini" | "cfg" | "conf" | "config" => Some("settings"),
        "editorconfig" => Some("editorconfig"),
        "eslintrc" | "eslintignore" => Some("eslint"),
        "prettierrc" | "prettierignore" => Some("prettier"),
        "webpack" => Some("webpack"),
        "vite" => Some("vite"),
        "rollup" => Some("rollup"),
        "test" | "spec" => Some("test-js"),
        "txt" | "rst" => Some("document"),
        "pdf" => Some("pdf"),
        "doc" | "docx" => Some("word"),
        "png" | "jpg" | "jpeg" | "gif" | "webp" | "ico" | "bmp" => Some("image"),
        "mp4" | "webm" | "mov" | "avi" | "mkv" => Some("video"),
        "mp3" | "wav" | "flac" | "ogg" => Some("audio"),
        "ttf" | "otf" | "woff" | "woff2" | "eot" => Some("font"),
        "zip" | "tar" | "gz" | "rar" | "7z" => Some("zip"),
        "graphql" | "gql" => Some("graphql"),
        "proto" => Some("proto"),
        "tf" | "tfvars" | "hcl" => Some("terraform"),
        "k8s" => Some("kubernetes"),
        "pem" | "crt" | "cer" => Some("certificate"),
        "key" => Some("key"),
        _ => None,
    }
}

/// Folders that carry their own icon, lower case (acepe's `getSpecialFolderIconSrc`).
pub(super) fn special_folder(name: &str) -> Option<&'static str> {
    match name {
        "node_modules" => Some("folder-node"),
        "src" | "services" => Some("folder-src"),
        "lib" => Some("folder-lib"),
        "dist" | "build" | "out" => Some("folder-dist"),
        "public" | "static" => Some("folder-public"),
        "assets" | "images" | "img" => Some("folder-images"),
        "components" => Some("folder-components"),
        "pages" | "views" => Some("folder-views"),
        "routes" => Some("folder-routes"),
        "api" => Some("folder-api"),
        "styles" | "css" => Some("folder-css"),
        "scripts" => Some("folder-scripts"),
        "js" => Some("folder-javascript"),
        "ts" | "types" => Some("folder-typescript"),
        "tests" | "test" | "__tests__" | "spec" => Some("folder-test"),
        "config" | "configs" => Some("folder-config"),
        "utils" => Some("folder-utils"),
        "helpers" => Some("folder-helper"),
        "hooks" => Some("folder-hook"),
        "interfaces" => Some("folder-interface"),
        "models" => Some("folder-database"),
        "controllers" => Some("folder-controller"),
        "middleware" => Some("folder-middleware"),
        "plugins" => Some("folder-plugin"),
        "docs" | "documentation" => Some("folder-docs"),
        "examples" => Some("folder-examples"),
        "templates" => Some("folder-template"),
        "layouts" => Some("folder-layout"),
        "store" | "stores" => Some("folder-store"),
        "context" | "providers" => Some("folder-context"),
        "shared" => Some("folder-shared"),
        "core" => Some("folder-core"),
        "packages" | "modules" | "vendor" => Some("folder-packages"),
        ".git" => Some("folder-git"),
        ".github" => Some("folder-github"),
        ".vscode" => Some("folder-vscode"),
        ".idea" => Some("folder-intellij"),
        "docker" => Some("folder-docker"),
        "kubernetes" | "k8s" => Some("folder-kubernetes"),
        "terraform" => Some("folder-terraform"),
        "aws" => Some("folder-aws"),
        "android" => Some("folder-android"),
        "ios" => Some("folder-ios"),
        "mobile" => Some("folder-mobile"),
        "server" | "backend" => Some("folder-server"),
        "client" | "frontend" => Some("folder-client"),
        "functions" | "lambda" => Some("folder-functions"),
        "graphql" => Some("folder-graphql"),
        "prisma" => Some("folder-prisma"),
        "supabase" => Some("folder-supabase"),
        "firebase" => Some("folder-firebase"),
        "svelte" => Some("folder-svelte"),
        "vue" => Some("folder-vue"),
        "angular" => Some("folder-angular"),
        "next" => Some("folder-next"),
        "nuxt" => Some("folder-nuxt"),
        "astro" => Some("folder-astro"),
        _ => None,
    }
}

/// Every icon the map names, embedded.
pub(super) fn embedded(name: &str) -> Option<&'static [u8]> {
    Some(match name {
    "astro" => include_bytes!("../../assets/file-icons/astro.svg"),
    "audio" => include_bytes!("../../assets/file-icons/audio.svg"),
    "biome" => include_bytes!("../../assets/file-icons/biome.svg"),
    "bun" => include_bytes!("../../assets/file-icons/bun.svg"),
    "c" => include_bytes!("../../assets/file-icons/c.svg"),
    "certificate" => include_bytes!("../../assets/file-icons/certificate.svg"),
    "changelog" => include_bytes!("../../assets/file-icons/changelog.svg"),
    "clojure" => include_bytes!("../../assets/file-icons/clojure.svg"),
    "cmake" => include_bytes!("../../assets/file-icons/cmake.svg"),
    "console" => include_bytes!("../../assets/file-icons/console.svg"),
    "cpp" => include_bytes!("../../assets/file-icons/cpp.svg"),
    "csharp" => include_bytes!("../../assets/file-icons/csharp.svg"),
    "css" => include_bytes!("../../assets/file-icons/css.svg"),
    "dart" => include_bytes!("../../assets/file-icons/dart.svg"),
    "database" => include_bytes!("../../assets/file-icons/database.svg"),
    "deno" => include_bytes!("../../assets/file-icons/deno.svg"),
    "docker" => include_bytes!("../../assets/file-icons/docker.svg"),
    "document" => include_bytes!("../../assets/file-icons/document.svg"),
    "editorconfig" => include_bytes!("../../assets/file-icons/editorconfig.svg"),
    "elixir" => include_bytes!("../../assets/file-icons/elixir.svg"),
    "erlang" => include_bytes!("../../assets/file-icons/erlang.svg"),
    "eslint" => include_bytes!("../../assets/file-icons/eslint.svg"),
    "file" => include_bytes!("../../assets/file-icons/file.svg"),
    "folder" => include_bytes!("../../assets/file-icons/folder.svg"),
    "folder-android" => include_bytes!("../../assets/file-icons/folder-android.svg"),
    "folder-android-open" => include_bytes!("../../assets/file-icons/folder-android-open.svg"),
    "folder-angular" => include_bytes!("../../assets/file-icons/folder-angular.svg"),
    "folder-angular-open" => include_bytes!("../../assets/file-icons/folder-angular-open.svg"),
    "folder-api" => include_bytes!("../../assets/file-icons/folder-api.svg"),
    "folder-api-open" => include_bytes!("../../assets/file-icons/folder-api-open.svg"),
    "folder-astro" => include_bytes!("../../assets/file-icons/folder-astro.svg"),
    "folder-astro-open" => include_bytes!("../../assets/file-icons/folder-astro-open.svg"),
    "folder-aws" => include_bytes!("../../assets/file-icons/folder-aws.svg"),
    "folder-aws-open" => include_bytes!("../../assets/file-icons/folder-aws-open.svg"),
    "folder-client" => include_bytes!("../../assets/file-icons/folder-client.svg"),
    "folder-client-open" => include_bytes!("../../assets/file-icons/folder-client-open.svg"),
    "folder-components" => include_bytes!("../../assets/file-icons/folder-components.svg"),
    "folder-components-open" => include_bytes!("../../assets/file-icons/folder-components-open.svg"),
    "folder-config" => include_bytes!("../../assets/file-icons/folder-config.svg"),
    "folder-config-open" => include_bytes!("../../assets/file-icons/folder-config-open.svg"),
    "folder-context" => include_bytes!("../../assets/file-icons/folder-context.svg"),
    "folder-context-open" => include_bytes!("../../assets/file-icons/folder-context-open.svg"),
    "folder-controller" => include_bytes!("../../assets/file-icons/folder-controller.svg"),
    "folder-controller-open" => include_bytes!("../../assets/file-icons/folder-controller-open.svg"),
    "folder-core" => include_bytes!("../../assets/file-icons/folder-core.svg"),
    "folder-core-open" => include_bytes!("../../assets/file-icons/folder-core-open.svg"),
    "folder-css" => include_bytes!("../../assets/file-icons/folder-css.svg"),
    "folder-css-open" => include_bytes!("../../assets/file-icons/folder-css-open.svg"),
    "folder-database" => include_bytes!("../../assets/file-icons/folder-database.svg"),
    "folder-database-open" => include_bytes!("../../assets/file-icons/folder-database-open.svg"),
    "folder-dist" => include_bytes!("../../assets/file-icons/folder-dist.svg"),
    "folder-dist-open" => include_bytes!("../../assets/file-icons/folder-dist-open.svg"),
    "folder-docker" => include_bytes!("../../assets/file-icons/folder-docker.svg"),
    "folder-docker-open" => include_bytes!("../../assets/file-icons/folder-docker-open.svg"),
    "folder-docs" => include_bytes!("../../assets/file-icons/folder-docs.svg"),
    "folder-docs-open" => include_bytes!("../../assets/file-icons/folder-docs-open.svg"),
    "folder-examples" => include_bytes!("../../assets/file-icons/folder-examples.svg"),
    "folder-examples-open" => include_bytes!("../../assets/file-icons/folder-examples-open.svg"),
    "folder-firebase" => include_bytes!("../../assets/file-icons/folder-firebase.svg"),
    "folder-firebase-open" => include_bytes!("../../assets/file-icons/folder-firebase-open.svg"),
    "folder-functions" => include_bytes!("../../assets/file-icons/folder-functions.svg"),
    "folder-functions-open" => include_bytes!("../../assets/file-icons/folder-functions-open.svg"),
    "folder-git" => include_bytes!("../../assets/file-icons/folder-git.svg"),
    "folder-git-open" => include_bytes!("../../assets/file-icons/folder-git-open.svg"),
    "folder-github" => include_bytes!("../../assets/file-icons/folder-github.svg"),
    "folder-github-open" => include_bytes!("../../assets/file-icons/folder-github-open.svg"),
    "folder-graphql" => include_bytes!("../../assets/file-icons/folder-graphql.svg"),
    "folder-graphql-open" => include_bytes!("../../assets/file-icons/folder-graphql-open.svg"),
    "folder-helper" => include_bytes!("../../assets/file-icons/folder-helper.svg"),
    "folder-helper-open" => include_bytes!("../../assets/file-icons/folder-helper-open.svg"),
    "folder-hook" => include_bytes!("../../assets/file-icons/folder-hook.svg"),
    "folder-hook-open" => include_bytes!("../../assets/file-icons/folder-hook-open.svg"),
    "folder-images" => include_bytes!("../../assets/file-icons/folder-images.svg"),
    "folder-images-open" => include_bytes!("../../assets/file-icons/folder-images-open.svg"),
    "folder-intellij" => include_bytes!("../../assets/file-icons/folder-intellij.svg"),
    "folder-intellij-open" => include_bytes!("../../assets/file-icons/folder-intellij-open.svg"),
    "folder-interface" => include_bytes!("../../assets/file-icons/folder-interface.svg"),
    "folder-interface-open" => include_bytes!("../../assets/file-icons/folder-interface-open.svg"),
    "folder-ios" => include_bytes!("../../assets/file-icons/folder-ios.svg"),
    "folder-ios-open" => include_bytes!("../../assets/file-icons/folder-ios-open.svg"),
    "folder-javascript" => include_bytes!("../../assets/file-icons/folder-javascript.svg"),
    "folder-javascript-open" => include_bytes!("../../assets/file-icons/folder-javascript-open.svg"),
    "folder-kubernetes" => include_bytes!("../../assets/file-icons/folder-kubernetes.svg"),
    "folder-kubernetes-open" => include_bytes!("../../assets/file-icons/folder-kubernetes-open.svg"),
    "folder-layout" => include_bytes!("../../assets/file-icons/folder-layout.svg"),
    "folder-layout-open" => include_bytes!("../../assets/file-icons/folder-layout-open.svg"),
    "folder-lib" => include_bytes!("../../assets/file-icons/folder-lib.svg"),
    "folder-lib-open" => include_bytes!("../../assets/file-icons/folder-lib-open.svg"),
    "folder-middleware" => include_bytes!("../../assets/file-icons/folder-middleware.svg"),
    "folder-middleware-open" => include_bytes!("../../assets/file-icons/folder-middleware-open.svg"),
    "folder-mobile" => include_bytes!("../../assets/file-icons/folder-mobile.svg"),
    "folder-mobile-open" => include_bytes!("../../assets/file-icons/folder-mobile-open.svg"),
    "folder-next" => include_bytes!("../../assets/file-icons/folder-next.svg"),
    "folder-next-open" => include_bytes!("../../assets/file-icons/folder-next-open.svg"),
    "folder-node" => include_bytes!("../../assets/file-icons/folder-node.svg"),
    "folder-node-open" => include_bytes!("../../assets/file-icons/folder-node-open.svg"),
    "folder-nuxt" => include_bytes!("../../assets/file-icons/folder-nuxt.svg"),
    "folder-nuxt-open" => include_bytes!("../../assets/file-icons/folder-nuxt-open.svg"),
    "folder-open" => include_bytes!("../../assets/file-icons/folder-open.svg"),
    "folder-packages" => include_bytes!("../../assets/file-icons/folder-packages.svg"),
    "folder-packages-open" => include_bytes!("../../assets/file-icons/folder-packages-open.svg"),
    "folder-plugin" => include_bytes!("../../assets/file-icons/folder-plugin.svg"),
    "folder-plugin-open" => include_bytes!("../../assets/file-icons/folder-plugin-open.svg"),
    "folder-prisma" => include_bytes!("../../assets/file-icons/folder-prisma.svg"),
    "folder-prisma-open" => include_bytes!("../../assets/file-icons/folder-prisma-open.svg"),
    "folder-public" => include_bytes!("../../assets/file-icons/folder-public.svg"),
    "folder-public-open" => include_bytes!("../../assets/file-icons/folder-public-open.svg"),
    "folder-routes" => include_bytes!("../../assets/file-icons/folder-routes.svg"),
    "folder-routes-open" => include_bytes!("../../assets/file-icons/folder-routes-open.svg"),
    "folder-scripts" => include_bytes!("../../assets/file-icons/folder-scripts.svg"),
    "folder-scripts-open" => include_bytes!("../../assets/file-icons/folder-scripts-open.svg"),
    "folder-server" => include_bytes!("../../assets/file-icons/folder-server.svg"),
    "folder-server-open" => include_bytes!("../../assets/file-icons/folder-server-open.svg"),
    "folder-shared" => include_bytes!("../../assets/file-icons/folder-shared.svg"),
    "folder-shared-open" => include_bytes!("../../assets/file-icons/folder-shared-open.svg"),
    "folder-src" => include_bytes!("../../assets/file-icons/folder-src.svg"),
    "folder-src-open" => include_bytes!("../../assets/file-icons/folder-src-open.svg"),
    "folder-store" => include_bytes!("../../assets/file-icons/folder-store.svg"),
    "folder-store-open" => include_bytes!("../../assets/file-icons/folder-store-open.svg"),
    "folder-supabase" => include_bytes!("../../assets/file-icons/folder-supabase.svg"),
    "folder-supabase-open" => include_bytes!("../../assets/file-icons/folder-supabase-open.svg"),
    "folder-svelte" => include_bytes!("../../assets/file-icons/folder-svelte.svg"),
    "folder-svelte-open" => include_bytes!("../../assets/file-icons/folder-svelte-open.svg"),
    "folder-template" => include_bytes!("../../assets/file-icons/folder-template.svg"),
    "folder-template-open" => include_bytes!("../../assets/file-icons/folder-template-open.svg"),
    "folder-terraform" => include_bytes!("../../assets/file-icons/folder-terraform.svg"),
    "folder-terraform-open" => include_bytes!("../../assets/file-icons/folder-terraform-open.svg"),
    "folder-test" => include_bytes!("../../assets/file-icons/folder-test.svg"),
    "folder-test-open" => include_bytes!("../../assets/file-icons/folder-test-open.svg"),
    "folder-typescript" => include_bytes!("../../assets/file-icons/folder-typescript.svg"),
    "folder-typescript-open" => include_bytes!("../../assets/file-icons/folder-typescript-open.svg"),
    "folder-utils" => include_bytes!("../../assets/file-icons/folder-utils.svg"),
    "folder-utils-open" => include_bytes!("../../assets/file-icons/folder-utils-open.svg"),
    "folder-views" => include_bytes!("../../assets/file-icons/folder-views.svg"),
    "folder-views-open" => include_bytes!("../../assets/file-icons/folder-views-open.svg"),
    "folder-vscode" => include_bytes!("../../assets/file-icons/folder-vscode.svg"),
    "folder-vscode-open" => include_bytes!("../../assets/file-icons/folder-vscode-open.svg"),
    "folder-vue" => include_bytes!("../../assets/file-icons/folder-vue.svg"),
    "folder-vue-open" => include_bytes!("../../assets/file-icons/folder-vue-open.svg"),
    "font" => include_bytes!("../../assets/file-icons/font.svg"),
    "fsharp" => include_bytes!("../../assets/file-icons/fsharp.svg"),
    "git" => include_bytes!("../../assets/file-icons/git.svg"),
    "go" => include_bytes!("../../assets/file-icons/go.svg"),
    "go-mod" => include_bytes!("../../assets/file-icons/go-mod.svg"),
    "gradle" => include_bytes!("../../assets/file-icons/gradle.svg"),
    "graphql" => include_bytes!("../../assets/file-icons/graphql.svg"),
    "groovy" => include_bytes!("../../assets/file-icons/groovy.svg"),
    "haskell" => include_bytes!("../../assets/file-icons/haskell.svg"),
    "html" => include_bytes!("../../assets/file-icons/html.svg"),
    "image" => include_bytes!("../../assets/file-icons/image.svg"),
    "java" => include_bytes!("../../assets/file-icons/java.svg"),
    "javaclass" => include_bytes!("../../assets/file-icons/javaclass.svg"),
    "javascript" => include_bytes!("../../assets/file-icons/javascript.svg"),
    "jest" => include_bytes!("../../assets/file-icons/jest.svg"),
    "jsconfig" => include_bytes!("../../assets/file-icons/jsconfig.svg"),
    "json" => include_bytes!("../../assets/file-icons/json.svg"),
    "julia" => include_bytes!("../../assets/file-icons/julia.svg"),
    "key" => include_bytes!("../../assets/file-icons/key.svg"),
    "kotlin" => include_bytes!("../../assets/file-icons/kotlin.svg"),
    "kubernetes" => include_bytes!("../../assets/file-icons/kubernetes.svg"),
    "less" => include_bytes!("../../assets/file-icons/less.svg"),
    "license" => include_bytes!("../../assets/file-icons/license.svg"),
    "lock" => include_bytes!("../../assets/file-icons/lock.svg"),
    "lua" => include_bytes!("../../assets/file-icons/lua.svg"),
    "luau" => include_bytes!("../../assets/file-icons/luau.svg"),
    "makefile" => include_bytes!("../../assets/file-icons/makefile.svg"),
    "markdown" => include_bytes!("../../assets/file-icons/markdown.svg"),
    "nim" => include_bytes!("../../assets/file-icons/nim.svg"),
    "nodejs" => include_bytes!("../../assets/file-icons/nodejs.svg"),
    "npm" => include_bytes!("../../assets/file-icons/npm.svg"),
    "ocaml" => include_bytes!("../../assets/file-icons/ocaml.svg"),
    "pdf" => include_bytes!("../../assets/file-icons/pdf.svg"),
    "perl" => include_bytes!("../../assets/file-icons/perl.svg"),
    "php" => include_bytes!("../../assets/file-icons/php.svg"),
    "pnpm" => include_bytes!("../../assets/file-icons/pnpm.svg"),
    "postcss" => include_bytes!("../../assets/file-icons/postcss.svg"),
    "powershell" => include_bytes!("../../assets/file-icons/powershell.svg"),
    "prettier" => include_bytes!("../../assets/file-icons/prettier.svg"),
    "prisma" => include_bytes!("../../assets/file-icons/prisma.svg"),
    "proto" => include_bytes!("../../assets/file-icons/proto.svg"),
    "python" => include_bytes!("../../assets/file-icons/python.svg"),
    "r" => include_bytes!("../../assets/file-icons/r.svg"),
    "react" => include_bytes!("../../assets/file-icons/react.svg"),
    "react_ts" => include_bytes!("../../assets/file-icons/react_ts.svg"),
    "readme" => include_bytes!("../../assets/file-icons/readme.svg"),
    "rollup" => include_bytes!("../../assets/file-icons/rollup.svg"),
    "ruby" => include_bytes!("../../assets/file-icons/ruby.svg"),
    "rust" => include_bytes!("../../assets/file-icons/rust.svg"),
    "sass" => include_bytes!("../../assets/file-icons/sass.svg"),
    "scala" => include_bytes!("../../assets/file-icons/scala.svg"),
    "settings" => include_bytes!("../../assets/file-icons/settings.svg"),
    "stylus" => include_bytes!("../../assets/file-icons/stylus.svg"),
    "svelte" => include_bytes!("../../assets/file-icons/svelte.svg"),
    "svg" => include_bytes!("../../assets/file-icons/svg.svg"),
    "swift" => include_bytes!("../../assets/file-icons/swift.svg"),
    "table" => include_bytes!("../../assets/file-icons/table.svg"),
    "tailwindcss" => include_bytes!("../../assets/file-icons/tailwindcss.svg"),
    "terraform" => include_bytes!("../../assets/file-icons/terraform.svg"),
    "test-js" => include_bytes!("../../assets/file-icons/test-js.svg"),
    "tex" => include_bytes!("../../assets/file-icons/tex.svg"),
    "todo" => include_bytes!("../../assets/file-icons/todo.svg"),
    "toml" => include_bytes!("../../assets/file-icons/toml.svg"),
    "tsconfig" => include_bytes!("../../assets/file-icons/tsconfig.svg"),
    "tune" => include_bytes!("../../assets/file-icons/tune.svg"),
    "turborepo" => include_bytes!("../../assets/file-icons/turborepo.svg"),
    "typescript" => include_bytes!("../../assets/file-icons/typescript.svg"),
    "typescript-def" => include_bytes!("../../assets/file-icons/typescript-def.svg"),
    "video" => include_bytes!("../../assets/file-icons/video.svg"),
    "vite" => include_bytes!("../../assets/file-icons/vite.svg"),
    "vitest" => include_bytes!("../../assets/file-icons/vitest.svg"),
    "vue" => include_bytes!("../../assets/file-icons/vue.svg"),
    "webpack" => include_bytes!("../../assets/file-icons/webpack.svg"),
    "word" => include_bytes!("../../assets/file-icons/word.svg"),
    "xml" => include_bytes!("../../assets/file-icons/xml.svg"),
    "yaml" => include_bytes!("../../assets/file-icons/yaml.svg"),
    "yarn" => include_bytes!("../../assets/file-icons/yarn.svg"),
    "zig" => include_bytes!("../../assets/file-icons/zig.svg"),
    "zip" => include_bytes!("../../assets/file-icons/zip.svg"),
        _ => return None,
    })
}
