/// Each UI token and the VS Code keys it reads, first found wins.
pub const UI_KEYS: &[(&str, &[&str])] = &[
    ("page", &["editor.background"]),
    ("ink", &["editor.foreground", "foreground"]),
    ("card", &["sideBar.background", "editorWidget.background", "panel.background"]),
    ("card_strong", &["input.background", "editorWidget.background"]),
    ("muted", &["descriptionForeground", "editorLineNumber.foreground"]),
    ("accent", &["focusBorder", "textLink.foreground"]),
    ("info", &["terminal.ansiBlue", "editorInfo.foreground"]),
    ("danger", &["terminal.ansiRed", "editorError.foreground", "gitDecoration.deletedResourceForeground"]),
    ("success", &["terminal.ansiGreen", "gitDecoration.addedResourceForeground"]),
    ("warning", &["editorWarning.foreground", "notificationsWarningIcon.foreground", "terminal.ansiYellow"]),
    ("selection", &["editor.selectionBackground", "list.activeSelectionBackground"]),
    ("popover", &["editorHoverWidget.background", "editorWidget.background"]),
    ("shadow", &["widget.shadow"]),
    ("diff_added", &["diffEditor.insertedTextBackground", "diffEditor.insertedLineBackground"]),
    ("diff_removed", &["diffEditor.removedTextBackground", "diffEditor.removedLineBackground"]),
];

/// Each syntax name the editor paints and the TextMate scopes it reads, first matched wins.
pub const SYNTAX_SCOPES: &[(&str, &[&str])] = &[
    ("comment", &["comment"]),
    ("comment.doc", &["comment.block.documentation", "comment"]),
    ("keyword", &["keyword", "storage.type", "storage.modifier"]),
    ("operator", &["keyword.operator", "punctuation"]),
    ("string", &["string"]),
    ("string.escape", &["constant.character.escape", "string"]),
    ("string.regex", &["string.regexp", "string"]),
    ("string.special", &["string.other", "string"]),
    ("string.special.symbol", &["constant.other.symbol", "string"]),
    ("number", &["constant.numeric", "constant"]),
    ("boolean", &["constant.language.boolean", "constant.language", "constant"]),
    ("constant", &["variable.other.constant", "constant"]),
    ("type", &["entity.name.type", "support.type", "entity.name.class"]),
    ("type.builtin", &["support.type.primitive", "support.type", "entity.name.type"]),
    ("constructor", &["entity.name.class", "entity.name.type"]),
    ("function", &["entity.name.function", "support.function"]),
    ("function.method", &["entity.name.function.member", "entity.name.function"]),
    ("function.builtin", &["support.function.builtin", "support.function", "entity.name.function"]),
    ("function.macro", &["entity.name.function.macro", "entity.name.function"]),
    ("variable", &["variable.other.readwrite", "variable.other", "variable"]),
    ("variable.parameter", &["variable.parameter", "variable"]),
    ("variable.member", &["variable.other.property", "variable.other.member", "variable"]),
    ("variable.special", &["variable.language", "variable"]),
    ("property", &["variable.other.property", "support.type.property-name", "variable"]),
    ("attribute", &["entity.other.attribute-name", "meta.attribute"]),
    ("tag", &["entity.name.tag"]),
    ("punctuation", &["punctuation"]),
    ("punctuation.bracket", &["punctuation.section", "punctuation"]),
    ("punctuation.delimiter", &["punctuation.separator", "punctuation.terminator", "punctuation"]),
    ("punctuation.special", &["punctuation.definition", "punctuation"]),
    ("label", &["entity.name.label", "keyword"]),
    ("namespace", &["entity.name.namespace", "entity.name.type.module", "entity.name.type"]),
    ("title", &["markup.heading", "entity.name.section"]),
    ("link_text", &["markup.underline.link", "string.other.link"]),
    ("link_uri", &["markup.underline.link", "string"]),
    ("embedded", &["meta.embedded", "source"]),
];
